### ISSUE TITLE
404

### ISSUE THREAD

**Issue by robputer** [GitYong/meteor-videojs#1]
Hello - I'm getting a 404 on the 2 inserted VideoJS files:

<script type="text/javascript" src="/packages/yong_meteor-videojs.js?c32142c94b9adcbcc9838a036219cf2ce5318908"></script>

<link type="text/css" rel="stylesheet" href="video-js/video-js.css">

<script type="text/javascript" src="video-js/video.js"></script>

**Comment by bruceyongli** [comment]
Could you please tell me more? Which version of Meteor you using? Where did you see the error? ...

**Comment by bruceyongli** [comment]
I'm going to close this issue. Please let me know if you need more help.
