### ISSUE TITLE
error: No compatible build found

### ISSUE THREAD

**Issue by foysalit** [GitYong/meteor-videojs#3]
Hi,
I'm trying to install this package but keep hitting the following the error - 

```
While checking for yong:meteor-videojs@1.0.5:
error: No compatible build found
```

May be you need to bump the version number or something? any help is much appreciated. 
Thanks

**Comment by bruceyongli** [comment]
Thanks for your report!  Please use:

```
meteor add yong:meteor-videojs
```

or

```
meteor add yong:meteor-videojs@1.1.0
```
